### ISSUE TITLE
Is it possible to install on ubuntu?

### ISSUE THREAD

**Issue by kaizen89** [VolkerH/Multilabelling_HDF5_View#3]
Hi,
I am trying to install the dependencies on ubuntu using conda (4.3.30) but I'm having a lot of issues - some packages are not available, others are conflicting. Are you able to install the packages on another machine from scratch?
thanks

**Comment by VolkerH** [comment]
Hi,
I need to check, I haven't used this for a long time.

But first let me point out that the codebase for this repo is still Python 2.7 not Python 3.x. Somehow this doesn't seem to be specified in the `environment.yml` file. Did you create a Python 2.7 env?

**Comment by VolkerH** [comment]
I had a brief look, unfortunately PyQt4 does not seem to be available as a package on the Python package index for Ubuntu and I could also not find it in conda anymore. This will be the most difficult dependency. 

However, these days I would probably use napari anyway. At the time I wrote this, there was no layer-based viewer for python that I was aware of.
Have a look at the example here (which is also a bit older and may have to be updated for the latest version of napari). 
https://github.com/VolkerH/NapariPlayground , specifically https://github.com/VolkerH/NapariPlayground/blob/master/Multilabelling/multilabel.py
