### ISSUE TITLE
What's the best way to convert a tif /ome.tif image to hdf5 format?

### ISSUE THREAD

**Issue by kaizen89** [VolkerH/Multilabelling_HDF5_View#4]
What's the best way to convert a tif /ome.tif image to hdf5 format?
thanks

**Comment by VolkerH** [comment]
I would suggest using the `tifffile` libraray for reading and the `h5py` library for writing.
There is not a single "hdf5" format, it is a container format that can have internal structure. I tried to document the internal structure in the HDF5 file format that I was using for this viewer, but there is no specific tool to convert this (the tool was very specific to our application).

**Comment by VolkerH** [comment]
I also saw that you raised a similar issue with the vitesce viewer, where you gave a dropbox link to a sample image.

Here is a solution for viewing that requires napari, tifffile and imagecodecs

```
import tifffile
import napari

multichannel_image = tifffile.imread("/put_correct_path_here/testwebsite.ome.tif")

v = napari.Viewer()


for channel_nr, layer in enumerate(multichannel_image):
    v.add_image(layer, name=f"channel {channel_nr}", blending="additive")

napari.run()
```

and then you can assign different names and colour maps for each layer:

![kaizen89](https://user-images.githubusercontent.com/2210044/124919139-27f13480-dff6-11eb-8d8a-058d5e742370.gif)

So in summary, I recommend using napari over investing time to get my old viewer that is no longer maintained to install.

**Comment by kaizen89** [comment]
Thanks a lot for all your answers
